// Generated by the WOLips Templateengine Plug-in at 17-Sep-2024 11:09:01 am


import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {
	private static final long serialVersionUID = 1L;
	public String add="";
	public String name="";
	public Main(WOContext context) {
		super(context);
	}
	public WOComponent submitAction() {
		 return null;
	}
	
}
